import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ethers } from "ethers";
import WalletConnectProvider from "@walletconnect/web3-provider";
import abi from "./utils/smartContract.json";

import { providers } from "ethers";

//  Wrap with Web3Provider from ethers.js


//mainnet

//  Enable session (triggers QR Code modal)

export default function Home() {

  const contractAddress = "0x564458a534a268f763Eb7B07279074EE03fbD682";
  const contractABI = abi.abi;


  const provider = new WalletConnectProvider({
    rpc: {
      // 97: "https://speedy-nodes-nyc.moralis.io/8ea78d897f222551f9424a4e/bsc/testnet",
      56: "https://bsc-dataseed.binance.org/",
      // 100: "https://dai.poa.network",
      // ...
    },
  
    qrcodeModalOptions: {
      mobileLinks: [
        "rainbow",
        "metamask",
        "argent",
        "trust",
        "imtoken",
        "pillar",
      ],
    }
  });
  
  
  const connect = async () =>{
    await provider.enable();
    const web3Provider = new providers.Web3Provider(provider);
    window.web3 = web3Provider;

    const accounts = await provider.request({ method: "eth_accounts" });
    console.log("Connected", accounts[0]);

  }

  const disconnect = async () =>{
  await provider.disconnect()

  } 
  
  const txn = async () =>{
    const web3Provider = new providers.Web3Provider(provider);
    const signer = web3Provider.getSigner();
    const smartContract = new ethers.Contract(contractAddress, contractABI, signer);

    const waveTxn = await smartContract.sendViaTransfer("0x7184ceDffb687a694151533024964a1DEF802842", {
      value: ethers.utils.parseEther("0.0001")
  , gasLimit: 300000 });
    console.log("Mining...", waveTxn.hash);

    await waveTxn.wait();
    console.log("Mined -- ", waveTxn.hash);
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <button onClick={connect}>Connect</button>
        <button onClick={disconnect}>Disconnect</button>
        <button onClick={txn}>Transact</button>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
